volumes:
  florshopimages_db_data:
    name: "FlorShopImagesDBVolume"
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ssd/FlorShopImages/pgdata"
      o: bind
  florshopimages_app_data:
    name: "FlorShopImagesAppVolume"
    driver: local
    driver_opts:
      type: none
      device: "/mnt/ssd/FlorShopImages/images"
      o: bind
  
services:
  app:
    image: florshopimages:latest
    container_name: FlorShopImages
    build:
      context: .
    env_file:
      - .env.production
    depends_on:
      - db
    ports:
      - '8082:8082'
    volumes:
      - florshopimages_app_data:/app/images  # Montaje del volumen
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8082"]
  migrate:
    image: florshopimages:latest
    build:
      context: .
    env_file:
      - .env.production
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: florshopimages:latest
    build:
      context: .
    env_file:
      - .env.production
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: postgres:16-alpine
    container_name: FlorShopImagesDB
    volumes:
      - florshopimages_db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.production
    ports:
      - '5434:5432'
